Repository oasp/oasp4j, pull requests merged in 2018-08, with the labels that each got.

#617 IdRef feature for typesafe and expressive entity references
  modules/basic/src/main/java/io/oasp/module/basic/common/api/reference/GenericIdRef.java
  modules/basic/src/main/java/io/oasp/module/basic/common/api/reference/IdRef.java
  modules/basic/src/main/java/io/oasp/module/basic/common/api/reference/Ref.java
  modules/basic/src/test/java/io/oasp/module/basic/common/api/reference/IdRefTest.java
  modules/jpa-basic/src/main/java/io/oasp/module/jpa/dataaccess/api/JpaEntityManagerAccess.java
  modules/jpa-basic/src/main/java/io/oasp/module/jpa/dataaccess/api/JpaHelper.java
  modules/jpa-basic/src/main/java/io/oasp/module/jpa/dataaccess/api/JpaInitializer.java
  modules/jpa-dao/pom.xml
  modules/jpa-dao/src/main/java/io/oasp/module/jpa/dataaccess/api/GenericDao.java
  modules/jpa-dao/src/main/java/io/oasp/module/jpa/dataaccess/base/AbstractGenericDao.java
  modules/jpa-dao/src/test/java/io/oasp/example/TestApplication.java
  modules/jpa-dao/src/test/java/io/oasp/example/component/common/api/Bar.java
  modules/jpa-dao/src/test/java/io/oasp/example/component/common/api/Foo.java
  modules/jpa-dao/src/test/java/io/oasp/example/component/common/api/to/BarEto.java
  modules/jpa-dao/src/test/java/io/oasp/example/component/common/api/to/FooEto.java
  modules/jpa-dao/src/test/java/io/oasp/example/component/dataaccess/api/BarEntity.java
  modules/jpa-dao/src/test/java/io/oasp/example/component/dataaccess/api/FooEntity.java
  modules/jpa-dao/src/test/java/io/oasp/example/component/dataaccess/api/dao/BarDao.java
  modules/jpa-dao/src/test/java/io/oasp/example/component/dataaccess/impl/BarDaoTxBean.java
  modules/jpa-dao/src/test/java/io/oasp/example/component/dataaccess/impl/dao/BarDaoImpl.java
  modules/jpa-dao/src/test/java/io/oasp/example/general/common/api/TestApplicationEntity.java
  modules/jpa-dao/src/test/java/io/oasp/example/general/common/api/config/BeansDozerConfig.java
  modules/jpa-dao/src/test/java/io/oasp/example/general/dataaccess/api/TestApplicationPersistenceEntity.java
  modules/jpa-dao/src/test/java/io/oasp/module/jpa/dataaccess/api/JpaHelperTest.java
  modules/jpa-dao/src/test/java/io/oasp/module/jpa/dataaccess/base/AbstractGenericDaoTest.java
  modules/jpa-dao/src/test/java/io/oasp/module/jpa/dataaccess/base/TestDao.java
  modules/jpa-dao/src/test/java/io/oasp/module/jpa/dataaccess/base/TestDaoImpl.java
  modules/jpa-dao/src/test/java/io/oasp/module/jpa/dataaccess/base/TestEntity.java
  modules/jpa-dao/src/test/resources/config/app/application-default.properties
  modules/jpa-dao/src/test/resources/config/app/common/beans-common.xml
  modules/jpa-dao/src/test/resources/config/app/common/dozer-mapping.xml
  modules/jpa-dao/src/test/resources/config/app/dataaccess/beans-dataaccess.xml
  modules/jpa-dao/src/test/resources/config/app/dataaccess/beans-db-plain.xml
  modules/jpa-dao/src/test/resources/config/app/dataaccess/beans-jpa.xml
  modules/jpa/src/test/resources/config/app/common/dozer-mapping.xml
  modules/pom.xml
  modules/test-jpa/pom.xml
  modules/test-jpa/src/main/java/io/oasp/module/test/common/base/ComponentDbTest.java
  modules/test-jpa/src/main/java/io/oasp/module/test/common/base/DbTest.java
  modules/test-jpa/src/main/java/io/oasp/module/test/common/base/JpaTestInitializer.java
  modules/test-jpa/src/main/java/io/oasp/module/test/common/base/SubsystemDbTest.java
  modules/test-jpa/src/main/java/io/oasp/module/test/common/base/SystemDbTest.java
  modules/test-jpa/src/main/java/io/oasp/module/test/common/base/clean/AbstractTestCleaner.java
  modules/test-jpa/src/main/java/io/oasp/module/test/common/base/clean/TestCleaner.java
  modules/test-jpa/src/main/java/io/oasp/module/test/common/base/clean/TestCleanerImpl.java
  modules/test-jpa/src/main/java/io/oasp/module/test/common/base/clean/TestCleanerPlugin.java
  modules/test-jpa/src/main/java/io/oasp/module/test/common/base/clean/TestCleanerPluginFlyway.java
  modules/test-jpa/src/main/java/io/oasp/module/test/common/base/clean/TestCleanerPluginNone.java
  modules/test/pom.xml
  modules/test/src/main/java/io/oasp/module/test/common/base/BaseTest.java
  modules/test/src/main/java/io/oasp/module/test/common/base/ComponentTest.java
  modules/test/src/main/java/io/oasp/module/test/common/base/SubsystemTest.java
  modules/test/src/main/java/io/oasp/module/test/common/base/SystemTest.java
Labels: backlog

#670 #670: minimize dependencies
  modules/security/pom.xml
  modules/security/src/main/java/io/oasp/module/security/common/base/accesscontrol/AbstractAccessControlProvider.java
  modules/security/src/main/java/io/oasp/module/security/common/base/accesscontrol/AccessControlConfig.java
  modules/security/src/test/java/io/oasp/module/security/common/impl/accesscontrol/AccessControlSchemaTest.java
Labels: enhancement

#668 Fixes for PR #665
  boms/bom/pom.xml
  modules/jpa-basic/pom.xml
  templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/service/impl/config/WebSecurityBeansConfig.java
  templates/server/src/main/resources/archetype-resources/core/src/main/resources/application.properties
Labels: persistence, template

#679 Spring boot upgrade issue with mysql and postgresql (fix for issue #674)
  templates/server/src/main/resources/archetype-resources/core/src/main/resources/META-INF/orm.xml
  templates/server/src/main/resources/archetype-resources/core/src/main/resources/config/application.properties
Labels: bug, persistence, spring-boot

#678 Angular 6 template fails as it uses GET method of login
  templates/server/src/main/resources/archetype-resources/core/src/main/java/__packageInPathFormat__/general/service/impl/LoginController.java
Labels: enhancement, service, template

#675 #669: minimal and pragmatic solution
  modules/jpa/src/main/java/io/oasp/module/jpa/common/base/LegacyDaoQuerySupport.java
Labels: enhancement, persistence
